<?php 

use kartik\grid\GridView;
use yii\helpers\Html;
use yii\bootstrap\Modal;

echo GridView::widget([
	'dataProvider' => $dataProvider,
	'responsive'=>true,
	'hover'=>true,     
	'resizableColumns'=>false,
	'panel'=>['type'=>'primary', 'heading'=> $heading],
	'responsiveWrap' => false,        
	'toolbar' => [
            '{toggleData}',
            '{export}',   
    ],
    // 'exportConfig' => [
    //     GridView::HTML => ['filename' => $heading,],
    //     GridView::CSV => ['filename' => $heading,],
    //     GridView::TEXT => ['filename' => $heading,],
    //     GridView::EXCEL => ['filename' => $heading,], 
    //     GridView::PDF => [
    //         'label' => 'PDF',
    //         'showHeader' => true,
    //         'showPageSummary' => true,
    //         'showFooter' => true,
    //         'showCaption' => true,
    //         'filename' => $heading,
    //         'alertMsg' => 'The PDF export file will be generated for download.',
    //         'options' => ['title' => 'Portable Document Format'],
    //         'mime' => 'application/pdf',
    //         'config' => [
    //             'mode' => 'c',
    //             'format' => 'A4-L',
    //             'destination' => 'D',
    //             'marginTop' => 20,
    //             'marginBottom' => 20,
    //             'cssInline' => '.kv-wrap{padding:20px;}' .
    //                 '.kv-align-center{text-align:center;}' .
    //                 '.kv-align-left{text-align:left;}' .
    //                 '.kv-align-right{text-align:right;}' .
    //                 '.kv-align-top{vertical-align:top!important;}' .
    //                 '.kv-align-bottom{vertical-align:bottom!important;}' .
    //                 '.kv-align-middle{vertical-align:middle!important;}' .
    //                 '.kv-page-summary{border-top:4px double #ddd;font-weight: bold;}' .
    //                 '.kv-table-footer{border-top:4px double #ddd;font-weight: bold;}' .
    //                 '.kv-table-caption{font-size:1.5em;padding:8px;border:1px solid #ddd;border-bottom:none;}',
    //             'methods' => [
    //                 'SetHeader' => $heading,
    //                 'SetFooter' => '<li role="presentation" class="dropdown-footer">Generated by econsole, '.date('Y-m-d H-i-s T').'</li>',
    //             ],
    //             'options' => [
    //                 'title' => $heading,
    //                 'subject' => 'PDF export generated by econsole',
    //                 'keywords' => 'grid, export, yii2-grid, pdf'
    //             ],
    //             'contentBefore'=>'',
    //             'contentAfter'=>''
    //         ]
    //     ],
    //     GridView::JSON => ['filename' => $heading,],
    // ],
	'pager' => [
	    'firstPageLabel' => 'Awal',
	    'lastPageLabel'  => 'Akhir'
	],
	'pjax'=>true,
	'pjaxSettings'=>[
	    'options' => ['id' => 'view-akun-pjax', 'timeout' => 5000],
	],
	'showPageSummary'=>true,    
	'columns' => [
        [
            'attribute' => 'kd_pemda',
            'value' => function($model){
                return $model->kd_pemda.". ".$model->refPemda->name;
            }
        ],
        'nm_rek_3',
        // [
        //     'label' => 'Kode Rekening',
        //     'width' => '10%',
        //     'hAlign' => 'center',
        //     'value' => function($model){
        //         return $model['kd_rek_1'].$model['kd_rek_2'].$model['kd_rek_3'];
        //     }
        // ],
        // [
        //     'label' => 'Uraian',
        //     'attribute' => 'nm_akrual_3',
        //     'format' => 'raw',
        //     'value' => function($model) use($getparam){
        //         if($model['nm_akrual_3'] == '[--Rekening Tidak Terdaftar--]'){
        //             $return = '<code>'.$model['nm_akrual_3'].'</code>';
        //         }else{
        //             $return = $model['nm_akrual_3'];
        //         }
        //         return Html::a($return, ['view', 
        //             'id' => $model['kd_rek_1'].$model['kd_rek_2'].$model['kd_rek_3'], 
        //             'kd_laporan' => $getparam['Laporan']['Kd_Laporan']
        //         ], [
        //             'class' => 'akunDetail',
        //             'data-toggle'=>"modal",
        //             'data-target'=>"#myModal",
        //             'data-title'=> $model['kd_rek_1'].$model['kd_rek_2'].$model['kd_rek_3']." $return",
        //         ]);
        //     }
        // ],
        [
            'attribute' => 'realisasi',
            // 'label' => 'Sebelum Eliminasi',
            'format' => 'decimal',
            'hAlign' => 'right',
            'pageSummary' => true,
            // 'value' => function($model){
            //     return $model['realisasi_sebelum'] ? $model['realisasi_sebelum'] : 0;
            // }
        ],
	],
]); 
 ?>